general:
  prefix: "&4&lMaxStaff &8Â» "

messages:
  no-permission: "&cYou do not have permission to use this command."
  plugin-reload: "&aConfiguration successfully reloaded."
  subcommand-invalid: "&cInvalid subcommand. Use /maxstaff help."
  subcommand-specified: "&cPlease specify a subcommand."
  
staff:
  chat-enabled: true