general:
  prefix: "&4&lMaxStaff &8Â» "

messages:
  no-permission: "&cYou do not have permission to use this command."
  plugin-reload: "&aConfiguration successfully reloaded."
  subcommand-invalid: "&cInvalid subcommand. Use /maxstaff help."
  subcommand-specified: "&cPlease specify a subcommand."

#MaxStaff Configuration
staff-mode:
  enabled: "&aStaff Mode ACTIVATED!"
  disabled: "&cStaff Mode DISABLED"
  inventory-saved: "&eYour inventory has been saved."
  inventory-restored: "&eYour inventory has been restored."
  cannot-drop: "&cYou cannot throw items in staff mode."
  cannot-place: "&cYou cannot place blocks in staff mode."

  items:
    punish:
      name: "&c&lSanction &7(Right Click)"
      slot: 0 
      message: "&eOpening the sanctions menu..."
    players:
      name: "&b&lPlayers &7(Right Click)"
      slot: 4 
      message: "&eOpening player menu..."
    inspect:
      name: "&6&lInspect &7(Click Jugador)"
      slot: 7 
      message: "&6Inspecting: &f{player}"
    vanish:
      name: "&a&lVanish &7(Click to toggle)"
      on-name: "&a&lVanish: ACTIVATED"
      off-name: "&7&lVanish: DISABLED"
      message-on: "&aVanish: ACTIVATED &7(You are invisible)" 
      message-off: "&cVanish: DISABLED &7(You are visible)"
      slot: 8 
  