# ==========================================
#        MaxStaff - Technical Configuration
# ==========================================

general:
  #The plugin's global prefix
  prefix: "&4&lMaxStaff &8Â» "
  #Check for updates on startup?
  update-check: true
  #Plugin language (Options: en, es)
  #The plugin will look for the file in: lang/messages_{language}.yml
  language: "en" 

# ==========================================
#        Database (MySQL)
# ==========================================
# IMPORTANT: For users who had plugin version 1.4.1, 
# when migrating to MySQL all sanction data will be deleted; that is, the sanction history will be blank.
database:
  enabled: false # If false, it will use the original file system (data.yml).
  host: "localhost"
  port: 3306
  database: "maxstaff_db"
  username: "root"
  password: ""
  use-ssl: false

#Material Configuration for Staff Mode
staff-mode:
  items:
    punish:
      material: "NETHERITE_HOE"
    freeze:
      material: "PACKED_ICE"
      helmet-material: "PACKED_ICE"
    players:
      material: "CLOCK"
    inspect:
      material: "CHEST"
    vanish:
      material: "NETHER_STAR"

#Technical configuration of GUIs (Materials)
gui:
  info:
    items:
      stats:
        material: "BOOK"
      history:
        material: "PAPER"
      action_punish:
        material: "NETHERITE_SWORD"
      alts:
        material: "COMPASS"
      inventory:
        material: "CHEST"

#Visual Style and Navigation (Materials Only)
gui-style:
  border-material: "BLACK_STAINED_GLASS_PANE"
  navigation:
    back-material: "BOOK"
    next-material: "ARROW" 
    prev-material: "ARROW"
  unified-menu:
    #Materials for long-lasting dyes in the reasons menu
    duration-1-material: "LIME_DYE"    #Short time
    duration-2-material: "YELLOW_DYE"  #Medium time
    duration-3-material: "ORANGE_DYE"  #Long time
    duration-4-material: "RED_DYE"     #Permanent

gui-gamemode: #Game Mode Menu Configuration
  enabled-menu: true #Enable/Disable the GUI menu
  survival-material: "GRASS_BLOCK"
  creative-material: "BEACON"
  adventure-material: "MAP"
  spectator-material: "ENDER_EYE"
  
#Sanctions System (Logic)
punishments:
  #Announce sanctions globally?
  broadcast: true
  broadcasts:
    warns:
      #Commands executed automatically upon reaching X warnings
      thresholds:
        3: "mute {target} 1h Accumulation of 3 warnings"
        5: "kick {target} You have exceeded the warning limit (5)"

#Definition of Sanction Reasons
#Here you define the ID, the Material, and the available Durations.
#The names ('name') can be translated directly here as they follow the logic.
punishment-reasons:
  BAN:
    xray: { name: "&6X-Ray", material: "DIAMOND_ORE", durations: ["7d", "14d", "30d", "perm"] }
    combat: { name: "&cCombat Hacks", material: "NETHERITE_SWORD", durations: ["30d", "60d", "90d", "perm"] }
    movement: { name: "&bMovement Hacks", material: "FEATHER", durations: ["14d", "30d", "60d", "perm"] }
    scripts: { name: "&eScripts", material: "NETHERITE_PICKAXE", durations: ["7d", "14d", "30d", "perm"] }
    griefing: { name: "&aGriefing", material: "TNT", durations: ["14d", "30d", "perm", "perm"] }
    theft: { name: "&7Theft", material: "CHEST", durations: ["7d", "14d", "30d", "perm"] }
    toxicity: { name: "&4Toxicity", material: "WITHER_SKELETON_SKULL", durations: ["14d", "30d", "perm", "perm"] }
    bugs: { name: "&dBugs", material: "BEDROCK", durations: ["7d", "30d", "perm", "perm"] }
    advertising: { name: "&9Advertising", material: "PAPER", durations: ["perm", "perm", "perm", "perm"] }
    evasion: { name: "&fEvasion", material: "IRON_BARS", durations: ["perm", "perm", "perm", "perm"] }
  MUTE:
    insults: { name: "&eInsults", material: "WRITABLE_BOOK", durations: ["1h", "12h", "1d", "7d"] }
    spam: { name: "&bSpam", material: "RECOVERY_COMPASS", durations: ["30m", "1h", "6h", "1d"] }
    flood: { name: "&3Flood", material: "WATER_BUCKET", durations: ["15m", "30m", "1h", "12h"] }
    toxic_chat: { name: "&cChat Toxicity", material: "POISONOUS_POTATO", durations: ["1h", "6h", "1d", "7d"] }
    language: { name: "&7Language", material: "SPORE_BLOSSOM", durations: ["1h", "2h", "6h", "12h"] }
    ads: { name: "&9Ads", material: "MAP", durations: ["12h", "1d", "7d", "30d"] }
    provocation: { name: "&6Provocation", material: "CAMPFIRE", durations: ["2h", "6h", "1d", "7d"] }
    discussions: { name: "&8Discussions", material: "SCULK_SENSOR", durations: ["1h", "3h", "12h", "1d"] }
    caps: { name: "&fCaps", material: "WHITE_WOOL", durations: ["15m", "30m", "1h", "3h"] }
    annoyance: { name: "&dAnnoyance", material: "GOAT_HORN", durations: ["1h", "12h", "1d", "7d"] }
  KICK:
    spam_ads: { name: "&eSpam/Publicidad", material: "PAPER", durations: ["inst"] }
    inappropriate_skin: { name: "&6Skin Inapropiada", material: "LEATHER_CHESTPLATE", durations: ["inst"] }
    bad_behavior: { name: "&cMal Comportamiento", material: "BONE", durations: ["inst"] }
    trolling: { name: "&dUser Trolling", material: "SLIME_BALL", durations: ["inst"] }